### ISSUE TITLE
Not working on iOS devices

### ISSUE THREAD

**Issue by ngjuping** [metastackio/analytics#2]
I have tried changing to CanvasRenderer in the main.js file, but no luck. Can you show me how to make it work on iOS devices?

**Comment by ngjuping** [comment]
To be specific, it is not running on iPadOS 14.7.1 ,iOS 14.7.1

**Comment by jaredmcqueen** [comment]
yeah, and it won't.  But it is possible, there are plenty of gpgpu examples on threejs.org that work with mobile.
